notifications:
  email:
    on_success: never
    on_failure: always

sudo: false
install: true

addons:
  sonarcloud:
    organization: "javaboilerplates"
    token:
      secure: $SONARCLOUD_TOKEN

language: java

jdk:
  - oraclejdk8

install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
 - ./mvnw test -B

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -DskipTests=true

before_deploy:
  - ./mvnw clean deploy

deploy:
  local-dir: target/mvn-repo
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master